src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
#[ORM\Table(name: '`employee`')]
#[Vich\Uploadable]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Employee implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 90)]
    private ?string $firstname = null;

    #[ORM\Column(length: 120)]
    private ?string $lastname = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_banned = null;

    #[Vich\UploadableField(mapping: 'profiles', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $imageName = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_MODERATOR';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        if ($plainPassword) {
            $this->updatedAT = new \DateTime('now');
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function isIsBanned(): ?bool
    {
        return $this->is_banned;
    }

    public function setIsBanned(?bool $is_banned): self
    {
        $this->is_banned = $is_banned;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAT = new \DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setProfileImageName(?UploadedFile $profileImage = null): self
    {
        $this->imageName = $profileImage ? $profileImage->getClientOriginalName() : null;

        return $this;
    }

}

src/Entity/OrderDetails.php
<?php

namespace App\Entity;

use App\Repository\OrderDetailsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderDetailsRepository::class)]
class OrderDetails
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orderDetails', fetch: 'EAGER')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $orderId = null;

    #[ORM\ManyToOne(inversedBy: 'orderDetails', fetch: 'EAGER')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $productId = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\Column]
    private string $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderId(): ?Order
    {
        return $this->orderId;
    }

    public function setOrderId(?Order $orderId): self
    {
        $this->orderId = $orderId;

        return $this;
    }

    public function getProductId(): ?Product
    {
        return $this->productId;
    }

    public function setProductId(?Product $productId): self
    {
        $this->productId = $productId;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return OrderDetails
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }
}

src/Controller/Back/ProductController.php
<?php

namespace App\Controller\Back;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/product')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository, 
    PaginatorInterface $paginator,
    Request $request): Response
    {
        $data = $productRepository->findBy([], ['id' => 'DESC']);
        $products = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            3
        );

        return $this->render('back/product/index.html.twig', [
            'products' =>  $products,
        ]);
    }

    #[Route('/{id}', name: 'app_product_show', methods: ['GET'])]
    public function show(Request $request, Product $product, ProductRepository $productRepository): Response
    {
        return $this->render('back/product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/ban', name: 'app_product_ban', methods: ['GET'])]
    public function ban(Request $request, Product $product, ProductRepository $productRepository): Response
    {

        if($product->isIsBanned() == true){
            $product->setIsBanned(false);
            $productRepository->save($product, true);
            $this->addFlash('success', 'Product unbanned successfully');
            return $this->redirectToRoute('admin_app_product_index', [], Response::HTTP_SEE_OTHER);
        }
        $product->setIsBanned(true);
        $productRepository->save($product, true);

        $this->addFlash('warning', 'Product banned successfully');

        return $this->redirectToRoute('admin_app_product_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/{id}/verify', name: 'app_product_verify', methods: ['GET'])]
    public function verify(Request $request, Product $product, ProductRepository $productRepository): Response
    {

        if($product->isIsValid() == true){
            $this->addFlash('success', 'Product already verified');
            return $this->redirectToRoute('admin_app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        $product->setIsValid(true);
        $productRepository->save($product, true);

        $this->addFlash('success', 'Product verified successfully');

        return $this->redirectToRoute('admin_app_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/CartController.php
<?php

namespace App\Controller\Front;

use App\Entity\Cart;
use App\Entity\OrderHistory;
use App\Entity\OrderState;
use App\Entity\Product;
use App\Repository\CartRepository;
use App\Repository\ProductRepository;
use App\Services\StripeService;
use Doctrine\ORM\EntityManagerInterface;
use Stripe\Exception\ApiErrorException;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security as SecurityGranted;


use App\Entity\Order;
use App\Entity\OrderDetails;

#[Route('/cart')]
class CartController extends AbstractController
{
    /**
     * @throws ApiErrorException
     */
    #[Route('/create/order', name: 'app_cart_create_order', methods: ['POST'])]
    #[SecurityGranted("is_granted('ROLE_USER')")]
    public function createOrder(EntityManagerInterface $em, ProductRepository $productRepository,  MailerInterface $mailer): Response
    {
        $cart = $this->getUser()->getCart();
        $total = 0;


        $orderHistory = new OrderHistory();
        $status = $em->getRepository(OrderState::class)->find(1);

        $stripeService = new StripeService();
        $resource = $productRepository->stripePayment($_POST);

        if($resource !== null){
            $totalPrice = array_reduce($cart->getProducts()->toArray(), function($sum, $product) {
                return $sum + $product->getPrice();
            }, 0.0);
            $productTitles = implode(', ', array_map(function($product) {
                return $product->getTitle();
            }, $cart->getProducts()->toArray()));
            $order = new Order();
            $order->setOwner($this->getUser());

            $order->setTotalPaid($total);
            $order->setTotalPaid($totalPrice + ($totalPrice * 0.2));
            $order->setBrandStripe($resource['stripeBrand']);
            $order->setLast4Stripe($resource['stripeLast4']);
            $order->setIdChargeStripe($resource['stripeId']);
            $order->setStripeToken($resource['stripeToken']);
            $order->setStatusStripe($resource['stripeStatus']);
            $order->setReference();
            $order->setCreatedAt(new \DateTime());
            $order->setUpdatedAt(new \DateTime());

           
            // Loop through products in cart and add them to order
            $receipt_details = array(); 
            foreach ($cart->getProducts() as $product) {
                $orderDetail = new OrderDetails();
                $orderDetail->setOrderId($order);
                $orderDetail->setDescription($productTitles);
                $orderDetail->setProductId($product);
                $orderDetail->setPrice($product->getPrice());
                $total += $product->getPrice();
                $em->persist($orderDetail);
                
                $receipt_details[] = array(
                    'title' => $product->getTitle(),
                    'amount' => $product->getPrice(),
                );

                // Remove product from cart
                $cart->removeProduct($product);
                $em->persist($cart);
            }

    
            //send email
            $email = (new TemplatedEmail())
                ->from(new Address('no-reply@vgcreator.fr', 'PixelFusion'))
                ->to($this->getUser()->getEmail())
                ->subject('Confirmation de votre commande')
                ->htmlTemplate('front/order/order_receipt.html.twig')
                ->context([
                    'order' => $order,
                    'receipt_details' => $receipt_details,
                ])
            ;

            $mailer->send($email);


            $orderHistory->setOrders($order);
            $orderHistory->setState($status);
            $orderHistory->setTimestamp(new \DateTime());

            $em->persist($order);
            $em->persist($orderHistory);
            $em->flush();

            $this->addFlash('success', 'Votre commande a bien été prise en compte');
            return $this->redirect('/orders');
        } else{
            return $this->redirect('/cart', 500);
        }
    }


    /**
     * @throws ApiErrorException
     */
    #[Route('/', name: 'app_cart_show', methods: ['GET'])]
    #[SecurityGranted("is_granted('ROLE_USER')")]
    public function show(ProductRepository $productRepository): Response
    {
        $cart = $this->getUser()->getCart();
        $cart_products = $cart->getProducts()->toArray();
        return $this->render('front/cart/show.html.twig', [
            'cart' => $cart,
            'intentSecret'=> count($cart_products) > 0?
                $productRepository->getIntentSecret($cart_products):
                null
        ]);
    }

    #[Route('/new/{id}', name: 'app_cart_new', methods: ['GET', 'POST'])]
    #[SecurityGranted("is_granted('ROLE_USER')")]
    public function new(Product $product, CartRepository $cartRepository): Response
    {
        $user = $this->getUser();
        if ($user->getCart()) {
            $cart = $user->getCart();
        } else {
            $cart = new Cart();
            $cart->setOwner($user);
        }
        $cart->addProduct($product);
        $cartRepository->save($cart, true);
        return $this->redirectToRoute('front_app_cart_show', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_cart_delete', methods: ['POST'])]
    #[SecurityGranted("is_granted('ROLE_USER')")]
    public function delete(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        $cart = $this->getUser()->getCart();
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $cart->removeProduct($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('front_app_cart_show', [],Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Product;
use App\Repository\ProductRepository;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(ProductRepository $productRepository, CategoryRepository $categoryRepository): Response
    {
        return $this->render('front/default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'last_products' => $productRepository->getLastProducts(1),
            'categories' => $categoryRepository->findBy([], null, 2),
            'five_last_products' => $productRepository->getLastProducts(5),
            'random_products' => $productRepository->getRandomProducts(5),
        ]);
    }

}

src/Controller/Front/OrderController.php
<?php

namespace App\Controller\Front;

use App\Entity\Order;
use App\Repository\OrderRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/orders')]
class OrderController extends AbstractController
{
    #[Route('/', name: 'app_order_show', methods: ['GET'])]
    #[Security("is_granted('ROLE_USER')")]
    public function index(OrderRepository $orderRepository): Response
    {
        $orders = $orderRepository->findAll();
        return $this->render('front/user_account/history.html.twig', [
            'orders' => $orders,
        ]);
    }
}

templates/front/product/_delete_form.html.twig
<form method="post" action="{{ path('front_app_product_delete', {'slug': product.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="mt-6 px-4 mx-24 py-2 w-64 rounded-md text-center bg-red-300 text-white hover:bg-red-500">Delete</button>
</form>

templates/front/product/_form.html.twig
<div class="mx-24">
{{ form_start(form) }}
    <div class="flex my-4 items-center gap-5">
        {{ form_errors(form.isActive) }}
        {{ form_label(form.isActive) }}
        {{ form_widget(form.isActive) }}
        {{ form_help(form.isActive) }}
    </div>
    <div class="flex flex-col my-4">
        {{ form_errors(form.title) }}
        {{ form_label(form.title) }}
        {{ form_widget(form.title) }}
        {{ form_help(form.title) }}
    </div>
    <div class="flex flex-col my-4">
        {{ form_errors(form.description) }}
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
        {{ form_help(form.description) }}
    </div>
    <div class="flex flex-col my-4">
        {{ form_errors(form.price) }}
        {{ form_label(form.price) }}
        {{ form_widget(form.price) }}
        {{ form_help(form.price) }}
    </div>
    <div class="flex flex-col my-4">
        {{ form_errors(form.imageFile) }}
        {{ form_label(form.imageFile) }}
        {{ form_widget(form.imageFile) }}
        {{ form_help(form.imageFile) }}
    </div>
    <div class="flex flex-col my-4">
        {{ form_errors(form.category) }}
        {{ form_label(form.category) }}
        {{ form_widget(form.category) }}
        {{ form_help(form.category) }}
    </div>
    <div class="flex gap-5">
        <button class="mt-6 px-4 py-2 w-64 rounded-md text-center bg-emerald-600 text-white hover:bg-emerald-700">{{ button_label|default('save') | trans }}</button>
        <a class="mt-6 px-4 py-2 w-64 rounded-md text-center bg-slate-400 text-white hover:bg-slate-600" href="{{ path('front_app_product_index') }}">{{ 'back_to_list' | trans }}</a>
    </div>
    {{ form_end(form) }}
</div>

templates/front/product/_formUpdate.html.twig
<div class="mx-24">
<h2 class="text-2xl font-bold my-2">Informations du produit</h2>
    <div class="mb-8">
        {% if product.isValid %}
            <div>- Produit Validé ✅</div>
        {% endif %}
        {% if product.isBanned %}
            <div>- Produit Banni ❌</div>
        {% endif %}
    </div>
{{ form_start(form, {'attr': {'class': 'flex justify-between gap-24 max-md:flex-col'}}) }}
    <div class="flex-1">
        <div class="flex flex-col my-4">
            {{ form_errors(form.imageFile) }}
            {{ form_label(form.imageFile) }}
            {{ form_widget(form.imageFile) }}
            {{ form_help(form.imageFile) }}
        </div>
    </div>
    <div class="flex-1">
        <div class="flex flex-col my-4">
            {{ form_errors(form.isActive) }}
            {{ form_label(form.isActive) }}
            {{ form_widget(form.isActive) }}
            {{ form_help(form.isActive) }}
        </div>
        <div class="flex flex-col my-4">
            {{ form_errors(form.title) }}
            {{ form_label(form.title) }}
            {{ form_widget(form.title) }}
            {{ form_help(form.title) }}
        </div>
        <div class="flex flex-col my-4">
            {{ form_errors(form.description) }}
            {{ form_label(form.description) }}
            {{ form_widget(form.description) }}
            {{ form_help(form.description) }}
        </div>
        <div class="flex flex-col my-4">
            {{ form_errors(form.price) }}
            {{ form_label(form.price) }}
            {{ form_widget(form.price) }}
            {{ form_help(form.price) }}
        </div>
        <div class="flex flex-col my-4">
            {{ form_errors(form.category) }}
            {{ form_label(form.category) }}
            {{ form_widget(form.category) }}
            {{ form_help(form.category) }}
        </div>
        <div class="flex gap-5">
            <button class="mt-6 px-4 py-2 w-64 rounded-md text-center bg-emerald-600 text-white hover:bg-emerald-700">{{ button_label|default('Save') }}</button>
            <a class="mt-6 px-4 py-2 w-64 rounded-md text-center bg-slate-400 text-white hover:bg-slate-600" href="{{ path('front_app_seller') }}">Back to List</a>
        </div>
    </div>
    {{ form_end(form) }}
    {{ include('front/product/_delete_form.html.twig') }}
</div>

templates/front/product/edit.html.twig
{% extends 'front_base.html.twig' %}

{% block body %}
    <h1 class="text-3xl font-bold text-center py-8">{{ 'edit_product'|trans }}</h1>

    {{ include('front/product/_formUpdate.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/front/product/index.html.twig
{% extends 'front_base.html.twig' %}

{% block body %}
<main>
	<!-- Category section -->
	<section aria-labelledby="category-heading" class="bg-gray-50">
		<div class="relative bg-slate-100 py-32 px-6 sm:py-24 sm:px-12 lg:px-16">
			<label class="block uppercase tracking-wide text-gray-700 text-2xl font-bold mb-2 text-center pb-4">
				{{ 'discover'|trans }}
			</label>
			<form class="relative">
				<input class="rounded-full border-gray-300 bg-white focus:outline-none w-full py-4 px-8"
				type="search" name="search" placeholder="Forest 2D, Pixel art">
				<input class="py-4 px-8 rounded-full cursor-pointer absolute right-0 top-0 border border-emerald-400 font-bold hover:border-emerald-600 transition bg-emerald-600 text-white hover:bg-emerald-700" value="{{ 'search'|trans }}" type="submit">
			</form>
		</div>
	</section>

	<!-- Favorites section -->
	<section aria-labelledby="favorites-heading">
		<div class="mx-auto max-w-7xl py-24 px-4 sm:py-32 sm:px-6 lg:px-8">
			<div class="sm:flex sm:items-baseline sm:justify-between">
				<h2 id="favorites-heading" class="text-2xl font-bold tracking-tight text-gray-900">
					{{ products|length }} Digital Assets {% if category is not null %}
						for category {{ category }}
					{% endif %}
				</h2>
				{% if app.request.query.get('search') is not null %}
					<div class="mt-4 sm:mt-0 sm:ml-4">
						<a href="{{ path('front_app_product_index') }}" class="hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block">
							Browse more assets
							<span aria-hidden="true"> &rarr;</span>
						</a>
					</div>
				{% endif %}
			</div>

			<div class="mt-6 grid grid-cols-1 gap-y-10 sm:grid-cols-4 sm:gap-y-4 sm:gap-x-6 lg:gap-x-8">

				{% for product in products %}
					<div class="group relative">
						<div class="h-48 w-full overflow-hidden rounded-lg group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-2 sm:h-auto">
							<img src="{{ vich_uploader_asset(product, 'imageFile') | imagine_filter('my_watermark_filter') }}" alt="{{ product.title }}"
								class="h-full w-full object-cover object-top" />
						</div>
						<h3 class="mt-4 text-base font-semibold text-gray-900">
							<a href={{ path('front_app_product_show', {'slug': product.slug})  }}>
								<span class="absolute inset-0"></span>
								{{ product.title }}
							</a>
						</h3>
						<p class="mt-1 text-sm text-gray-500">{{product.price}} €</p>
					</div>
				{% endfor %}

				{% if products|length == 0 %}
					<div class="group relative">
						<h3 class="mt-4 text-base font-semibold text-gray-900">
							{{ 'products_not_found'|trans }}
						</h3>
						<p class="mt-1 text-sm text-gray-500">
							{{ category ? "Try another category": "Try another search parameter" }}
							<a href={{ path('front_app_product_index', {'search': app.request.query.get('search')}) }} class="text-sm font-semibold text-indigo-600 hover:text-indigo-500">
								{{ app.request.query.get('search') }}
							</a>
						</p>
					</div>
				{% endif %}

				<div class="mt-6 sm:hidden">
					<a href="#" class="block text-sm font-semibold text-indigo-600 hover:text-indigo-500">
						Browse all favorites
						<span aria-hidden="true"> &rarr;</span>
					</a>
				</div>
			</div>
		</div>
	</section>
</main>
{% endblock %}

templates/front/product/new.html.twig
{% extends 'front_base.html.twig' %}

{% block body %}

    <h1 class="text-3xl font-bold text-center py-8">Create new Product</h1>

    {{ include('front/product/_form.html.twig') }}
{% endblock %}